"""empty message

Revision ID: 331835d3a390
Revises: a1fe2cd9f499
Create Date: 2024-10-24 18:01:46.072892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331835d3a390'
down_revision = 'a1fe2cd9f499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('estimated_cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_cost', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
