"""empty message

Revision ID: ca8ef4a670f9
Revises: 92d26d584a61
Create Date: 2024-10-25 14:35:27.333353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca8ef4a670f9'
down_revision = '92d26d584a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskhours', schema=None) as batch_op:
        batch_op.drop_column('billable_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskhours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billable_type', postgresql.ENUM('BILLABLE', 'NON_BILLABLE', 'BOTH', name='billabletype'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
